### ISSUE TITLE
Cant use it.

### ISSUE THREAD

**Issue by iosfritz** [axi0mX/alloc8#2]
I wanted to downgade my iphone 3gs from 2009 to 3.1.3. 
I folliwed your tutorial went to dfu mode then used -p to get into pwned dfu mode. After this I wanted to restore in itunes eih this firmware. There I get an error cos of the signing.
So I thought it should be possible with alloc8 to downgrade to any version I like?
Whats the problem how I am doing it?

**Comment by axi0mX** [comment]
Closing, since an issue for ipwndfu was opened:

https://github.com/axi0mX/ipwndfu/issues/35
